# Generated by Django 5.0.7 on 2024-07-10 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medition',
            name='altitude',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='medition',
            name='battery',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='medition',
            name='temperature',
            field=models.IntegerField(),
        ),
    ]
