# Generated by Django 5.0.7 on 2024-07-13 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0002_alter_medition_altitude_alter_medition_battery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medition',
            name='aceleration_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='medition',
            name='aceleration_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='medition',
            name='aceleration_z',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='medition',
            name='gyro_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='medition',
            name='gyro_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='medition',
            name='gyro_z',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='medition',
            name='medition',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medition',
            name='pressure',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='medition',
            name='time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medition',
            name='altitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='medition',
            name='temperature',
            field=models.FloatField(default=0.0),
        ),
    ]
